// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB3FSBV_HqbvaEMh8UEAGCY8gpW6D0TlA',
    appId: '1:275330405289:web:c175cf672359eace6a2ab8',
    messagingSenderId: '275330405289',
    projectId: 'app-3-adb8e',
    authDomain: 'app-3-adb8e.firebaseapp.com',
    storageBucket: 'app-3-adb8e.appspot.com',
    measurementId: 'G-R80GHMLZT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMjhkQBV6opC1Afqt3CmpzGWnkpr6ugSQ',
    appId: '1:275330405289:android:7ad4a3c8791219846a2ab8',
    messagingSenderId: '275330405289',
    projectId: 'app-3-adb8e',
    storageBucket: 'app-3-adb8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByQUMmBWzJXCqlGYB59T47cJIIUFRom3Y',
    appId: '1:275330405289:ios:82c84e19d634f8d16a2ab8',
    messagingSenderId: '275330405289',
    projectId: 'app-3-adb8e',
    storageBucket: 'app-3-adb8e.appspot.com',
    androidClientId: '275330405289-1mj170gil3crojbl5rgulodtj0mmk79n.apps.googleusercontent.com',
    iosClientId: '275330405289-ob5ai2esnpgrs4c31174n1bggvv3aqep.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByQUMmBWzJXCqlGYB59T47cJIIUFRom3Y',
    appId: '1:275330405289:ios:82c84e19d634f8d16a2ab8',
    messagingSenderId: '275330405289',
    projectId: 'app-3-adb8e',
    storageBucket: 'app-3-adb8e.appspot.com',
    androidClientId: '275330405289-1mj170gil3crojbl5rgulodtj0mmk79n.apps.googleusercontent.com',
    iosClientId: '275330405289-ob5ai2esnpgrs4c31174n1bggvv3aqep.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
